# Generated by Django 3.1.6 on 2021-02-15 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('continent', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('edittime', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Study', '留学'), ('Travel', '旅行')], default='留学', max_length=200)),
                ('img', models.ImageField(blank=True, null=True, upload_to='blog_images', verbose_name='博客配图')),
                ('conn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.country')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-edittime'],
            },
        ),
    ]
