# Generated by Django 3.1.6 on 2021-02-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='博客配图'),
        ),
    ]
