# Generated by Django 3.1.6 on 2021-02-21 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20210222_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Country', to='stock.country'),
        ),
    ]
